### ISSUE TITLE
Have subsections for FAQ/Code Questions

### ISSUE THREAD

**Issue by astrale-sharp** [godot-rust/gdnative-book#48]
I think it would be a good idea to do this so users could see all the different common code answers in one look and easily click on them in the menu. It might be a good idea for other sections as well.

What do you think?

**Comment by Bromeon** [comment]
What do you mean exactly? _Common code questions_ is already its own page, and there are some changes coming in https://github.com/godot-rust/book/pull/46.

Also, you have opened 3 issues and 3 PRs (mostly empty) in the last two days. If you want to discuss the book's structure in greater detail, maybe consider joining the Discord? We'd like to keep issues as a way to track known problems and PRs as ready-to-use implementations -- neither issues nor PRs should be the primary discussion platform for vague topics. Thank you! 🙂

**Comment by jacobsky** [comment]
@astrale-sharp Thank you for the interest. This issue is a bit too vague/brainstormy for an issue. Missing topics or questions that aren't covered are more appropriate for issues. If you have ideas for additions, reorganizations or guides, please feel free to create a first draft of the changes and open a PR as a draft so that we can give our feedback, it would be a lot easier to actually judge the changes that way.

**Comment by astrale-sharp** [comment]
I'm didn't mean to mess up the way you do things ! sorry about that! By all means, I'll join the discord server and discuss things here instead and/or open draft with contents for reviewing if that's okay!
I thought it would serve to make clear that i planned to do something here but i should have asked before!
