### ISSUE TITLE
Frequently asked questions

### ISSUE THREAD

**Issue by ghost** [godot-rust/gdnative-book#5]
- [ ] `Instance`
- [ ] User-data errors (`BorrowFailed`, `DifferentThread`)

...and more?

**Comment by bluenote10** [comment]
Perhaps another topic for the FAQ: How to use the Godot profiler for native functions?

From what I can see (and also this [Q/A](https://godotengine.org/qa/66606/preformance-of-gdnative-plugin-not-showing-in-profiler)), native functions/classes are not automatically visible in the profiler. Since the majority of my business logic runs in Rust, the output of Godot's built-in profiler isn't very useful so far. [This example](https://github.com/godotengine/godot-cpp/blob/master/include/core/GodotProfiling.hpp) suggests, that on C++ side there is a `Godot::gdnative_profiling_add_data(signature, t)` function, which looks like providing functionality for manually adding profiling data (which wouldn't be too bad). What I couldn't figure out so far is where it is coming from, and if there is an equivalent in the Rust bindings.

**Comment by ghost** [comment]
I don't think there is a high-level interface to `gdnative_profiling_add_data` in the Rust bindings yet. We might be able to add one, but native profilers (e.g. `perf`) will probably be much more accurate and informative than Godot's internal profiling when it comes to profiling Rust code. If we decide to add the profiling topic to the FAQ, I would prefer that native profilers be recommended.

**Comment by bluenote10** [comment]
> native profilers (e.g. perf) will probably be much more accurate and informative than Godot's internal profiling when it comes to profiling Rust code.

Good point. I guess there are use cases for both. What is nice about the built-in profiler:
- easy to compare GDScript vs GDNative runtime.
- understand the notion of a frame, which can be useful.
- easy to use, just a mouse click away and convenient output.

I'll try to contribute a minimal integration...
